usernameInput = input("Username :")
passwordInput = input("Password :")
if usernameInput == "ad" and passwordInput == "min" :
    print("Done")
    print("welcome to the shop")
    print("---- Our product----")
    print("Apple   10THB/Kg")
    print("Banana  20THB/Kg")
    print("Mango   30THB/Kg")
    print("Kiwi    40THB/Kg")
    a = int(input("How many apple do you want?(Kg):"))
    b = int(input("How many banana do you want?(Kg):"))
    m = int(input("How many mango do you want?(Kg):"))
    k = int(input("How many kiwi do you want?(Kg):"))
    print("Price for Apple:", a*10,"THB")
    print("Price for Banana:", b*20, "THB")
    print("Price for Mango:", m*30, "THB")
    print("Price for Kiwi:", k*40, "THB")
    print("Total:", a*10 + b*20 + m*30 + k*40 , "THB,")
else:
    print("Eror")